# Assignment 6.3: Intro to Jupyter Notebooks and practice with advanced numpy

## Before starting: Import the numpy library


In [2]:
import numpy as np

## Exercise 1: Create a 3D numpy array and print it
### Create a 3D array with shape (2, 3, 4) filled with random numbers

In [5]:
arr3d = np.random.randint(1, 100, size=(2,3,4))

arr3d

array([[[20, 44, 86, 85],
        [48, 74, 84, 76],
        [63, 89,  4, 90]],

       [[14, 22,  8, 59],
        [58, 48, 56, 24],
        [13,  8, 39, 67]]])

## Exercise 2: Perform boolean indexing on a 2D array

### Create a 2D array and filter out elements less than 0.5

In [10]:
arr = np.random.random(size=(2,5))
print(arr)
arr[arr<0.5]

[[0.94391018 0.42824515 0.86772959 0.73727512 0.8793521 ]
 [0.2809434  0.33655249 0.89376052 0.0981157  0.54491903]]


array([0.42824515, 0.2809434 , 0.33655249, 0.0981157 ])

## Exercise 3: Reshape an array from 1D to 3D and print the new array


In [13]:
x = np.arange(1, 91)
y = x.reshape(3,30)
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
        47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

## Exercise 4: Calculate and print the variance and standard deviation of a 1D array


## Exercise 5: Calculate the sum across columns of a 2D array


## Exercise 6: Calculate and print the correlation coefficient between two 1D arrays
